# Generated by Django 4.1.5 on 2023-01-17 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LookupObjects',
            fields=[
                ('objectID', models.IntegerField(primary_key=True, serialize=False)),
                ('objectName', models.CharField(max_length=40)),
                ('objectDes', models.CharField(max_length=60)),
                ('isReadOnly', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': 'Look-up Object',
                'verbose_name_plural': 'Look-up Objects',
                'db_table': 'LookupObjects',
            },
        ),
        migrations.CreateModel(
            name='LookupData',
            fields=[
                ('dataID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dataDes', models.CharField(max_length=100, verbose_name='Data Description')),
                ('isDefault', models.BooleanField(default=0)),
                ('isHidden', models.BooleanField(default=0)),
                ('objectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.lookupobjects')),
            ],
            options={
                'verbose_name': 'Look-up Data',
                'verbose_name_plural': 'Look-up Data',
                'db_table': 'LookupData',
            },
        ),
    ]
