# Generated by Django 4.1.5 on 2023-01-18 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('allergyno', models.CharField(db_column='AllergyNo', max_length=20, primary_key=True, serialize=False)),
                ('allergyname', models.CharField(blank=True, db_column='AllergyName', max_length=60, null=True, unique=True)),
                ('allergycategoryid', models.ForeignKey(blank=True, db_column='AllergyCategoryID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.lookupdata')),
            ],
            options={
                'verbose_name': 'Allergy',
                'verbose_name_plural': 'Allergies',
                'db_table': 'Allergies',
            },
        ),
    ]
